# Generated by Django 4.0.5 on 2022-06-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_in', models.DateField(auto_now=True)),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=15)),
                ('imagen', models.ImageField(upload_to='photos')),
                ('cedula_p', models.CharField(max_length=15)),
                ('nombre_p', models.CharField(max_length=25)),
                ('apellido_p', models.CharField(max_length=25)),
                ('contacto_p', models.CharField(max_length=15)),
            ],
        ),
    ]
