# Generated by Django 4.0.5 on 2022-06-04 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.origen'),
        ),
    ]
