# Generated by Django 4.0.5 on 2022-06-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_origen_vehiculo_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='apellido_p',
            field=models.CharField(max_length=25, verbose_name='Apellido de propietario'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cedula_p',
            field=models.CharField(max_length=15, verbose_name='Cedula de propietario'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=15, verbose_name='Color de vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='contacto_p',
            field=models.CharField(max_length=15, verbose_name='Contacto propietario'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=20, verbose_name='Marca de vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=20, verbose_name='Modelo de vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='nombre_p',
            field=models.CharField(max_length=25, verbose_name='Nombre de propietario'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10, verbose_name='Placa de vehiculo'),
        ),
    ]
